version = "One" # This option will be deprecated in Rustfmt 2.0. A useful warning if and when that comes!

format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
imports_granularity = "Module"
merge_derives = true
newline_style = "Unix"
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
